global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "food-pricing-api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: /metrics

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
